"""Render docs/phase1_report.md from bronze manifest + profile. Numbers come only from those files."""
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[3]
B = ROOT / "data" / "bronze"

def jl(p):
    return [json.loads(l) for l in p.read_text().splitlines() if l.strip()] if p.exists() else []

def main():
    hosp = {h["slug"]: h for h in yaml.safe_load((ROOT / "config/hospitals.yaml").read_text())["hospitals"]}
    man = jl(B / "manifest.jsonl")
    ok = {r["slug"]: r for r in man if r.get("outcome") in ("stored", "unchanged_duplicate")}
    fails = {}
    for r in man:
        if r.get("outcome") == "failed":
            fails.setdefault(r["slug"], []).append(r["error"][:90])
    prof = {p["slug"]: p for p in jl(B / "profile.jsonl")}
    rows = []
    for slug, h in hosp.items():
        r, p = ok.get(slug), prof.get(slug, {})
        rows.append((h["group"], slug, h["state"],
                     f'{r["size_bytes"]/1e6:,.1f}' if r else "-",
                     "zip" if r and r["filename"].endswith(".zip") else (r["filename"].rsplit(".", 1)[-1] if r else "-"),
                     p.get("layout", "not profiled"), p.get("declared_version") or "-",
                     f'{(p.get("data_rows") or p.get("standard_charge_items") or 0):,}' if p else "-",
                     f'{r["duration_s"]:,.0f}' if r else "-",
                     f'{r["robots"]["status"]}' if r else "-"))
    tot = sum(r["size_bytes"] for r in ok.values())
    out = ["# Phase 1 report (generated by `pricecheck.ingest.report`; do not edit by hand)\n",
           f"Stored: **{len(ok)} of {len(hosp)}** hospital files, **{tot/1e9:,.2f} GB** total as downloaded.\n",
           "| group | slug | st | MB | container | layout | declared ver | rows / items | download s | robots.txt HTTP |",
           "|---|---|---|---:|---|---|---|---:|---:|---|"]
    out += ["| " + " | ".join(map(str, r)) + " |" for r in rows]
    if fails:
        out += ["", "## Failed download attempts (recorded, not hidden)"]
        out += [f"- `{s}`: {len(e)} failed manifest entr{'y' if len(e)==1 else 'ies'}; last: {e[-1]}" for s, e in fails.items()]
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs/phase1_report.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))

if __name__ == "__main__":
    main()
