"""Render docs/phase2_report.md from silver/run_log.jsonl (numbers only from that log)."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[3]

def main():
    runs = {}
    for l in (ROOT / "data/silver/run_log.jsonl").read_text().splitlines():
        r = json.loads(l); runs[r["slug"]] = r          # latest per slug
    tot_in = sum(r["source_rows_in"] for r in runs.values()); tot_out = sum(r["rows_out"] for r in runs.values())
    tot_rej = sum(r["rejects"] for r in runs.values())
    out = ["# Phase 2 report (generated by `pricecheck.silver.report`; do not edit by hand)\n",
           f"{len(runs)} sources; **{tot_in:,}** source rows -> **{tot_out:,}** canonical price rows; **{tot_rej:,}** rejects; "
           f"{sum(r['outcome']=='quarantined' for r in runs.values())} quarantined.\n",
           "| slug | layout | ver | source rows | canonical rows | rejects | reject reasons | cp1252-fallback bytes | non-$ negotiated cells | seconds |",
           "|---|---|---|---:|---:|---:|---|---:|---:|---:|"]
    for s, r in sorted(runs.items()):
        out.append(f"| {s} | {r['layout']} | {r['template_version']} | {r['source_rows_in']:,} | {r['rows_out']:,} | {r['rejects']:,} | "
                   f"{', '.join(f'{k}={v}' for k, v in r['reject_reasons'].items()) or '-'} | {r['encoding_fallback_bytes']} | "
                   f"{r['non_dollar_negotiated_cells']:,} | {r['duration_s']} |")
    (ROOT / "docs/phase2_report.md").write_text("\n".join(out) + "\n"); print("\n".join(out[:4]))

if __name__ == "__main__":
    main()
