from pathlib import Path

from deltalake import DeltaTable

from pricecheck.history import delta_store as D

ROOT = Path(__file__).resolve().parents[1]
rows = sorted(D.ledger_records(ROOT / "data/delta/ingestion_ledger"), key=lambda r: r["history_version_after"])
con = D.duck(); p = ROOT / "data/delta/price_history"
tot, cur, hosp = con.execute(f"select count(*), count(*) filter (is_current), count(distinct hospital_slug) from delta_scan('{p}')").fetchone()
out = ["# Phase 3 report (generated by `scripts/phase3_report.py`; do not edit by hand)\n",
       f"History table: **{tot:,}** rows, **{cur:,}** current, **{hosp}** hospitals, Delta version **{DeltaTable(str(p)).version()}**; ledger entries: {len(rows)}.\n",
       "| slug | mode | staged rows | inserted | closed | unchanged | table version after | seconds | synthetic |", "|---|---|---:|---:|---:|---:|---:|---:|---|"]
out += [f"| {r['slug']} | {r['mode']} | {r['staged_rows']:,} | {r['rows_inserted']:,} | {r['rows_closed']:,} | {r['rows_unchanged']:,} | {r['history_version_after']} | {r['duration_s']} | {r['synthetic']} |" for r in rows]
(ROOT / "docs/phase3_report.md").write_text("\n".join(out) + "\n"); print("\n".join(out[:3]))
