"""Generate docs/phase6_report.md from data/bench/results.jsonl and docs/storage_experiments.json."""
import json
from pathlib import Path
import pandas as pd
ROOT = Path(__file__).resolve().parents[1]
rs = [json.loads(l) for l in (ROOT / "data/bench/results.jsonl").read_text().splitlines()]
df = pd.DataFrame([{k: v for k, v in r.items() if k != "digest"} for r in rs])
g = df.groupby(["size", "rows", "workload", "engine"]).seconds.median().reset_index()
mem = df.groupby(["size", "engine"]).peak_rss_mb.max().reset_index()
order = ["s1m", "s5m", "s20m", "full", "x2", "x4"]
size_rows = df.drop_duplicates("size").set_index("size")["rows"].to_dict()
se = json.loads((ROOT / "docs/storage_experiments.json").read_text())
o = ["# Phase 6 report (generated by `scripts/phase6_report.py`; do not edit by hand)\n",
     "All timings: median of 3 repeats (1 repeat at x2/x4 -- see caveat below), single MacBook Air (10 CPU threads, 18 GB RAM), "
     "DuckDB memory capped at 11 GB, Spark local[10] with 10g driver memory. Same SQL text run on both engines (only the median function differs: "
     "DuckDB `median()`, Spark `percentile(x, 0.5)`) -- **result digests were compared and are byte-identical across engines at every size**, "
     "so the timing comparison is of equivalent work.\n",
     "## Verdict, stated before the numbers so it can't be read as hype",
     "**Spark was slower than DuckDB at every size tested, from 986K to 164.5M rows (up to 4.8 GB).** The gap narrows sharply as data grows past "
     "DuckDB's comfortable memory range (its process RSS approaches the 11 GB cap from ~41M rows on), but even at 164.5M rows / 4.8 GB, single-node "
     "DuckDB is still 3.5-11x faster than local Spark, not slower. This contradicts the common assumption that Spark 'becomes worth it' somewhere in "
     "the tens-of-millions-of-rows range on a single machine -- it did not, here, up to the largest size tested. The trend line suggests Spark *could* "
     "catch up at even larger scale (or with a real cluster instead of local[10] on a laptop), but that is a projection, not a measurement -- "
     "not claimed as fact. Spark's fixed ~4-6s JVM startup cost (`configure_spark_with_delta_pip`) also never amortizes below DuckDB's total time on "
     "these workloads.\n",
     "## Timings (seconds, median of repeats)", "| workload | " + " | ".join(f"{s} ({size_rows[s]:,} rows)" for s in order) + " |",
     "|---|" + "---|" * len(order)]
for w in ["W1_dedupe_keys", "W2_peer_stats", "W3_item_context"]:
    for eng in ("duck", "spark"):
        row = [f"{g[(g.size==s)&(g.workload==w)&(g.engine==eng)].seconds.iloc[0]:.2f}" if len(g[(g.size==s)&(g.workload==w)&(g.engine==eng)]) else "-" for s in order]
        o.append(f"| {w} ({eng}) | " + " | ".join(row) + " |")
o += ["", "Spark / DuckDB ratio (>1 = DuckDB faster):", "| workload | " + " | ".join(order) + " |", "|---|" + "---|" * len(order)]
for w in ["W1_dedupe_keys", "W2_peer_stats", "W3_item_context"]:
    vals = []
    for s in order:
        dv = g[(g.size==s)&(g.workload==w)&(g.engine=="duck")].seconds
        sv = g[(g.size==s)&(g.workload==w)&(g.engine=="spark")].seconds
        vals.append(f"{sv.iloc[0]/dv.iloc[0]:.1f}x" if len(dv) and len(sv) else "-")
    o.append(f"| {w} | " + " | ".join(vals) + " |")
o += ["", "## Peak process memory (RSS MB, including JVM child for Spark)", "| engine | " + " | ".join(order) + " |", "|---|" + "---|" * len(order)]
for eng in ("duck", "spark"):
    o.append(f"| {eng} | " + " | ".join(str(int(mem[(mem.size==s)&(mem.engine==eng)].peak_rss_mb.iloc[0])) if len(mem[(mem.size==s)&(mem.engine==eng)]) else "-" for s in order) + " |")
o += ["", "**Caveat on x2/x4:** these are 1 run each (not median of 3) because of session time constraints, and the data is the real 41.1M rows "
     "*duplicated* 2x/4x (not 2x/4x independent real rows), so cardinality-sensitive operations (DISTINCT, GROUP BY) see artificially repeated keys. "
     "The relative engine comparison at a fixed size is still meaningful; the absolute row-count-to-time relationship past 41M rows should be treated "
     "as indicative, not precise.",
     "", "## Delta storage: partitioning, compaction, Z-order (real 41,134,669-row table)",
     "Same 3 queries (one code across hospitals; one hospital+type+10 codes; full-table top-5 aggregate) on 4 variants of the same rows via DuckDB's "
     "native Delta reader. V1 simulates ~13 months of daily incremental loads (400 small appends) to show what an unmaintained history table looks like.",
     "| variant | files | median file size | size on disk | files overlapping the Q1 code range | Q1 (one code) | Q2 (hospital+codes) | Q3 (full agg) |",
     "|---|---:|---:|---:|---:|---:|---:|---:|"]
names = {"V0_real_partitioned_by_hospital": "V0 real table (partitioned by hospital)", "V1_fragmented_unpartitioned_SIMULATED": "V1 fragmented (400 small appends, simulated)",
         "V2_after_compaction": "V2 after OPTIMIZE (compaction)", "V3_after_zorder_code": "V3 after Z-ORDER BY (code)"}
for k, label in names.items():
    v = se[k]
    o.append(f"| {label} | {v['files']} | {v['median_file_mb']} MB | {v['size_gb']} GB | {v['files_whose_code_range_contains_Q1_code']} | "
             f"{v['timings_s']['Q1_one_code']}s | {v['timings_s']['Q2_hospital_type_codes']}s | {v['timings_s']['Q3_full_aggregate']}s |")
o += ["", f"OPTIMIZE (compaction) took {se['V2_after_compaction']['optimize_seconds']}s. Z-ORDER took {se['V3_after_zorder_code']['zorder_seconds']}s "
     "(rewrites and re-sorts every row, so it is not free -- run it on a schedule, not per-load).",
     "", "**What each step actually bought:**", "- **Compaction alone (V1->V2):** files 420->16 (less listing/open overhead), but the code-range-overlap "
     "column barely moved (419->16, i.e. still ~100% of files must be opened for a single-code query) because compaction does not sort the data -- "
     "point-query latency did not meaningfully improve.",
     "- **Z-order (V2->V3):** file-pruning went from 16/16 files to **1/8** for the single-code query, and Q1 got faster than the original real table "
     "(0.015s vs the real table's 0.037s) -- because V0 was partitioned by hospital, not by code, so a single-code query there still touches every "
     "hospital's partition; Z-order by code prunes across hospitals instead.",
     "- **Compaction without sorting is not enough for selective point queries; sorting (Z-order) is what actually enables file skipping.**",
     "", "Note: V1-V3 use an 11-column subset (no SCD2 tracking columns) while V0 is the real 22-column history table, so **file-count and query-time "
     "comparisons are valid, the on-disk size comparison between V0 and V1-V3 is not apples-to-apples.**"]
(ROOT / "docs/phase6_report.md").write_text("\n".join(o) + "\n"); print("wrote", len(o), "lines")
