"""Generate docs/phase4_report.md from the measured JSON/CSV outputs (numbers are never typed by hand)."""
import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]; A = ROOT / "data/anomaly"
fs = json.loads((A / "features_summary.json").read_text()); ev = json.loads((A / "injection_eval.json").read_text())
rv = json.loads((A / "review_results.json").read_text()); sens = json.loads((A / "peer_threshold_sensitivity.json").read_text())
q = pd.read_csv(ROOT / "docs/quality_scores.csv").sort_values("quality_score", ascending=False)
o = ["# Phase 4 report (generated by `scripts/phase4_report.py`; do not edit by hand)\n",
     "## Coverage: what can be scored at all",
     "| price type | candidate rows (CPT/HCPCS/MS-DRG) | peer-scorable rows | coverage |", "|---|---:|---:|---:|"]
o += [f"| {k} | {fs['candidate_rows'][k]:,} | {fs['scored_rows'][k]:,} | {fs['coverage'][k]:.1%} |" for k in fs["scored_rows"]]
o += ["", "Peer group = same code, price type, setting, billing class at >= 5 hospitals and >= 30 rows. Unscored rows are **not** treated as normal.",
      "", f"## Recall on {ev['n_injected']:,} injected anomalies (thresholds fixed beforehand)",
      "| injected corruption | rules | isolation forest | combined |", "|---|---:|---:|---:|"]
o += [f"| {k} | {v['rules']:.1%} | {v['isolation_forest']:.1%} | {v['combined']:.1%} |" for k, v in ev["per_type"].items()]
r = ev["overall_recall"]
o += [f"| **all types pooled** | {r['rules']:.1%} | {r['isolation_forest']:.1%} | {r['combined']:.1%} |", "",
      "Peer-only (|robust z| >= 5) recall, no internal-consistency rules:", "| corruption | peer-only recall |", "|---|---:|"]
o += [f"| {k.split('/')[0]} | {v['peer_only_R1']:.1%} |" for k, v in ev["recall_by_item_context"].items() if k.endswith("with_item_context")]
n = ev["natural_flag_rate_on_clean_sample"]
o += ["", f"Natural flag rate on {n['n']:,} unmodified rows: rules {n['rules']:.1%}, isolation forest {n['isolation_forest']:.1%}, combined {n['combined']:.1%}.",
      "", "### Peer threshold sensitivity (negotiated prices, consistent unit error)", "| |z| threshold | natural flag rate | recall x10 | recall x100 |", "|---:|---:|---:|---:|"]
o += [f"| {s['threshold']} | {s['natural_flag_rate']:.1%} | {s['recall_x10']:.1%} | {s['recall_x100']:.1%} |" for s in sens]
o += ["", f"## Precision (AI-labeled review of {rv['n_reviewed']} flagged prices, NOT a human/domain-expert review)",
      "| first detector | flagged population | reviewed | likely error | cannot tell | plausible real | precision (E only .. E+U) | Wilson 95% (E only) |", "|---|---:|---:|---:|---:|---:|---|---|"]
o += [f"| {k} | {v['population']:,} | {v['reviewed']} | {v['E']} | {v['U']} | {v['R']} | {v['precision_low']:.0%}..{v['precision_high']:.0%} | {v['wilson95_low_bound'][0]:.0%}-{v['wilson95_low_bound'][1]:.0%} |" for k, v in rv["strata"].items()]
p = rv["overall_precision_estimate"]
o += [f"| **overall, stratum-weighted** | {p['flagged_population']:,} | {rv['n_reviewed']} | | | | {p['lower']:.0%}..{p['upper']:.0%} | |", "",
      "## Per-hospital quality score (0-100)", "| hospital | score | completeness | validity | consistency | freshness |", "|---|---:|---:|---:|---:|---:|"]
o += [f"| {r.hospital_slug} | {r.quality_score} | {r.completeness:.3f} | {r.validity:.3f} | {r.consistency:.3f} | {r.freshness:.3f} |" for r in q.itertuples()]
(ROOT / "docs/phase4_report.md").write_text("\n".join(o) + "\n"); print("wrote", len(o), "lines")
